### ISSUE TITLE
What's Missing?

### ISSUE THREAD

**Issue by remotevase** [remotevase/SignTP#1]
The [WORLD] sign works, but the [COORD] sign doesn't. I have added the code for the [COORD] sign completely, but it **still** doesn't work! Why? Can any1 help?

**Comment by remotevase** [comment]
@Taki21 this is what I needed help with!

**Comment by Taki21** [comment]
ok

**Comment by Taki21** [comment]
hmm

**Comment by Taki21** [comment]
Im checkin

**Comment by Taki21** [comment]
ok this may take a few

**Comment by Taki21** [comment]
im editin

**Comment by remotevase** [comment]
okay. I just took a hard look (spent 5 mins checking) and I realized that the server dispatch command may be in the wrong place

**Comment by remotevase** [comment]
I may have to go for 10 mins soon, but, as I just said: I'll be back in 10 mins XD

**Comment by Taki21** [comment]
fixed

**Comment by Taki21** [comment]
check now! : D

**Comment by Taki21** [comment]
ok

**Comment by remotevase** [comment]
Actually, I can't check. I have no access to an ImagicalMine server :( 
My Microsoft Azure subscription expired so SQPE and Dev SQPE wont be up for a few days
Is there any way that you can check?? I recommend tp-ing to the coordinates "125 124 123" because its completely random, and theyre all 3 digit numbers that are different

**Comment by Taki21** [comment]
ok ill check

**Comment by remotevase** [comment]
Check what I posted on ImagicalMine forums: https://forums.imagicalmine.net/threads/test-my-in-dev-plugins-thanks.668/

**Comment by remotevase** [comment]
So, does it work now? Sorry about being so urgent, but...

**Comment by dragonwocky** [comment]
I would test but I don't currently have access to my Pi, the soonest I can test is in about 8 hours

**Comment by remotevase** [comment]
k

**Comment by remotevase** [comment]
I reviewed the code again,and I'm sure it works. No update yet (gotta test) but soon...

**Comment by remotevase** [comment]
Currently only Main&New Features branch. Soon going to be in the rewrite branch as well
Not sure why this issue happens, though...

**Comment by remotevase** [comment]
new issue: #4
