### ISSUE TITLE
AAAAAAAAAAAAAHHHHHHHHHHHHHH

### ISSUE THREAD

**Issue by remotevase** [remotevase/SignTP#3]
HELPP ME HELP ME HELP ME!!!!!!!!

`critical> pocketmine\utils\PluginException: "Couldn't load plugin S-W_Ultimate: main class not found" (EXCEPTION) in "/src/pocketmine/plugin/PharPluginLoader" at line 75 
 emergency> An unrecoverable error has occurred and the server has crashed. Creating a crash dump`

**Comment by remotevase** [comment]
Calling the squad
@ImagicalGamer @Taki21 @TheDragonRing 
Calling my support team
@applqpak @plugingod

**Comment by dragonwocky** [comment]
Ok, I had a look, aaaaannnnnndddddd...........I don't get it :( but it looks like i might have that error with BOB later too (think I might have had it before as well), so I'll keep looking for a solution

**Comment by remotevase** [comment]
Maybe it's am issue with our plugin structure? I think I may be able to fix it, not sure though. It will require a bit of looking through other plugins that use a loader

**Comment by dragonwocky** [comment]
Well, @Sandertv (@Blabla) had the same error here - https://forums.imagicalmine.net/threads/problem-with-plugin.1010/ - and got it fixed by changing his namespace....

**Comment by remotevase** [comment]
Hmm, okay? I'll try that...

**Comment by Taki21** [comment]
use S-W-Ultimate\signs\worldtp;
use S-W-Ultimate\signs\coordtp;
use S-W-Ultimate\signs\status;
use S-W-Ultimate\signs\seedgenerate;
use S-W-Ultimate\signs\typegenerate;
use S-W-Ultimate\signs\cmd-non-op; #Can by tapped by any player, even if non-op player. Only runs non-op commands.
use S-W-Ultimate\signs\cmd-op; #Can only by tapped by ops. Runs any command, even op only commands
use S-W-Ultimate\signs\cmd-all; #Can by tapped by any player, even if non-op player. Runs any command.
use S-W-Ultimate\worldcmd\seedgenerate;
use S-W-Ultimate\worldcmd\typegenerate;
use S-W-Ultimate\worldcmd\worldtp;
use S-W-Ultimate\worldcmd\coordtp;
use S-W-Ultimate\worldcmd\worldload;
These classes dont exist?

**Comment by remotevase** [comment]
naw, I think I fixed. @Taki21 I said only in the V1 branch

**Comment by remotevase** [comment]
Fixed in latest commits
